# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af5280892afcd970575721ad37d8d7d516a1563d128e9516ce798357f05a964246536eadc248831e20052019854710c305a2e5fcdfdddc0f373130b1a178fcf

test:
  secret_key_base: f584fadd4648f30418f9095972afced56f9c3a5b265ed680412d39f09e5f67e54eeb7aba42df454c64dcc77d4d92a309ede55f6ab6238f213f7ba6bb5bd2b623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
